name: Pack and Release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package and Release
        uses: BigWigsMods/packager@master
        with:
          args: # Tell the packager where the topdir (and thus the toc file) is located
            -t "!!NoTaint2"
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
